name:                monomer-flatpak-example
version:             0.0.1.0
license:             MIT
synopsis:            Monomer Flatpak Example Application.
description:         An example of how to package Monomer apps with Flatpak.
github:              Dretch/monomer-flatpak-example
homepage:            https://github.com/Dretch/monomer-flatpak-example#readme
bug-reports:         https://github.com/Dretch/monomer-flatpak-example/issues
category:            GUI
maintainer:          garethdanielsmith@gmail.com

dependencies:
- base >= 4.7 && < 5
- containers
- directory
- monomer
- monomer-hagrid
- text

default-extensions:
- DisambiguateRecordFields
- DuplicateRecordFields
- FlexibleContexts
- LambdaCase
- NamedFieldPuns
- OverloadedRecordDot
- OverloadedStrings

executables:
  app:
    main: Main.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
