name:                monomer-flatpak-example
version:             0.0.12.0
license:             MIT
synopsis:            Monomer Flatpak Example Application.
description:         An example of how to package Monomer apps with Flatpak.
github:              Dretch/monomer-flatpak-example
homepage:            https://github.com/Dretch/monomer-flatpak-example#readme
bug-reports:         https://github.com/Dretch/monomer-flatpak-example/issues
category:            GUI, Flatpak
maintainer:          garethdanielsmith@gmail.com

dependencies:
- async
- base >= 4.7 && < 5
- bytestring
- containers
- data-default-class
- dbus
- desktop-portal >= 0.3.2.0 && < 0.4
- directory
- modern-uri
- monomer
- monomer-hagrid
- random
- text

default-extensions:
- BinaryLiterals
- DisambiguateRecordFields
- DuplicateRecordFields
- FlexibleContexts
- ImportQualifiedPost
- LambdaCase
- NamedFieldPuns
- NoFieldSelectors
- OverloadedRecordDot
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables

data-dir: assets
data-files: '**/*'

executables:
  monomer-flatpak-example:
    main: Main.hs
    source-dirs: app
    include-dirs:
    - cbits
    c-sources:
    - cbits/pipewire_hacks.c
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
    pkg-config-dependencies:
    - libspa-0.2
    - libpipewire-0.3
    build-tools: c2hs
