name:                monomer-flatpak-example
version:             0.0.1.0
license:             MIT

dependencies:
- base >= 4.7 && < 5
- containers
- directory
- monomer
- monomer-hagrid
- text

default-extensions:
- DisambiguateRecordFields
- DuplicateRecordFields
- FlexibleContexts
- LambdaCase
- NamedFieldPuns
- OverloadedRecordDot
- OverloadedStrings

library:
  source-dirs: src
  ghc-options: -O2 -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

executables:
  app:
    main: Main.hs
    source-dirs: app
    ghc-options: -O2 -threaded -rtsopts -with-rtsopts=-N -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
    dependencies:
      - monomer-flatpak-example
