name: Generate Flatpak Manifest

on: [workflow_dispatch]

jobs:
  generate-flatpak-manifest:

    runs-on: ubuntu-22.04

    steps:

    - name: 'Warning !!!'
      run: 'echo "This will only work once the package is published on Hackage!"'

    - uses: actions/checkout@v3
    
    - name: 'Install GHC'
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.2.5'

    - name: 'Install Libraries'
      run: sudo apt-get update && sudo apt-get install --assume-yes libsdl2-dev libglew-dev

    - name: 'Generate Manifest'
      run: cd flatpak && ./generate-manifest.sh

    - name: 'Archive Manifest'
      uses: actions/upload-artifact@v3
      with:
        name: flatpak-manifest
        path: |
          flatpak/README.md
          flatpak/flathub.json
          flatpak/io.github.Dretch.MonomerFlatpakExample.yml
        if-no-files-found: error
  
  make-pull-request:

    runs-on: ubuntu-22.04

    needs: [generate-flatpak-manifest]

    steps:

    - uses: actions/checkout@v3
      with:
        repository: flathub/io.github.Dretch.MonomerFlatpakExample

    - uses: actions/download-artifact@v3
      with:
        name: flatpak-manifest

    - name: 'Create Pull Request'
      uses: peter-evans/create-pull-request@v5
